### ISSUE TITLE
HFInferenceClientWorkflow init Parameter model Not Utilized

### ISSUE THREAD

**Issue by FWangZil** [ritual-net/infernet-ml#1]
**Description:**
When initializing `HFInferenceClientWorkflow`, the constructor accepts a parameter `model: Optional[str] = None`. However, the `model` value is not utilized in either the `__init__` or `do_setup` methods. As a result, requests sent to Hugging Face only use the default model for the specified task, rather than the model provided during initialization.

- **Environment:**
  - Library Version: v0.1.0
  - Python Version: Python3.11

- **Steps to Reproduce:**
  1. Initialize `HFInferenceClientWorkflow` with a specific model parameter.
  2. Execute the workflow setup.
  3. Observe that the specified model is not used in requests to Hugging Face.

- **Expected Behavior:**
  The `model` parameter should be used during initialization and setup to ensure requests are made using the specified model rather than the default model.

- **Actual Behavior:**
  The `model` parameter is ignored, and only the default model for the specified task is used in requests.

**Comment by stelios-ritual** [comment]
fixing in upcoming release, thanks!
